Fase2_ipcvacas/Models/ViewModels/EmpleadoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fase2_ipcvacas.Models.ViewModels
{
    public class EmpleadoViewModel
    {
        [Required]
        [StringLength(9)]
        [DisplayName("Nit")]
        public string nit { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Nombres")]
        public string nombres { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Apellidos")]
        public string apellidos { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "La {0} debe tener al menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        public string pass { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de nacimiento")]
        public DateTime fecha_nacimiento { get; set; }

        [Required]
        [DisplayName("Numero de domicilio")]
        public int numero_domicilio { get; set; }

        [Required]
        [DisplayName("Número de celular")]
        public int numero_celular { get; set; }

        [Required]
        [StringLength(50)]
        [EmailAddress]
        [DisplayName("Email")]
        public string correo { get; set; }

        [Required]
        [StringLength(75)]
        [DisplayName("Dirección")]
        public string direccion { get; set; }

        [Required]
        [DisplayName("Puesto")]
        public string puesto { get; set; } //campo que indica el superior

        [DisplayName("Nit de supervisor")]
        public string nit_supervisor { get; set; }

        [DisplayName("Nit de gerente")]
        public string nit_gerente { get; set; }

        
    }
}

Fase2_ipcvacas/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using Fase2_ipcvacas.Models.ViewModels;
using System.Xml;

namespace Fase2_ipcvacas.Controllers
{
    public class EmpleadoController : Controller
    {
        // conexión con base de datos
        string connectionString = @"Data Source=DESKTOP-UUIAD81; Initial Catalog= proyecto_ipc2beta4; Integrated Security=SSPI"; //SSPI por autenticación de Windows

        public ActionResult InicioEmpleado(EmpleadoViewModel empleado)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "select * from Empleado where nit = @nit";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@nit", Session["userNit"].ToString());
                using (SqlDataReader sdr = sqlCmd.ExecuteReader())
                {
                    if (sdr.Read()) //en este caso se usa if porque solo se obtiene un resultado
                    {
                        empleado.correo = sdr[7].ToString();
                    }
                }
                sqlCon.Close();
            }

            return View(empleado);
        }

        [HttpGet]
        public ActionResult Index()
        {

            DataTable dbEmpleados = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * FROM Empleado", sqlCon);
                sqlDa.Fill(dbEmpleados);
                sqlCon.Close();
            }

            return View(dbEmpleados);
        }


        // Enviando a la vista un nuevo objeto del modelo de Empleados
        [HttpGet]
        public ActionResult Create()
        {
            return View(new EmpleadoViewModel());
        }

        [HttpPost]
        public ActionResult Create(EmpleadoViewModel empleado)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                string nit_supervisor = empleado.nit_supervisor;
                string nit_gerente = empleado.nit_gerente;
                string puesto_empleado = empleado.puesto;

                sqlCon.Open();
                string query = "insert into Empleado values(@nit, @nombres, @apellidos, @pass, @fecha_nacimiento, @numero_domicilio, @numero_celular, @correo, @direccion, @nit_supervisor, @nit_gerente, @Puesto)";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@nit", empleado.nit);
                sqlCmd.Parameters.AddWithValue("@nombres", empleado.nombres);
                sqlCmd.Parameters.AddWithValue("@apellidos", empleado.apellidos);
                sqlCmd.Parameters.AddWithValue("@pass", empleado.pass);
                sqlCmd.Parameters.AddWithValue("@fecha_nacimiento", empleado.fecha_nacimiento);
                sqlCmd.Parameters.AddWithValue("@numero_domicilio", empleado.numero_domicilio);
                sqlCmd.Parameters.AddWithValue("@numero_celular", empleado.numero_celular);
                sqlCmd.Parameters.AddWithValue("@correo", empleado.correo);
                sqlCmd.Parameters.AddWithValue("@direccion", empleado.direccion);

                if (empleado.puesto == "Gerente")
                {
                    sqlCmd.Parameters.AddWithValue("@nit_supervisor", DBNull.Value);
                    sqlCmd.Parameters.AddWithValue("@nit_gerente", DBNull.Value);
                    sqlCmd.Parameters.AddWithValue("@Puesto", "Gerente");
                }
                else if (empleado.puesto == "Supervisor")
                {
                    sqlCmd.Parameters.AddWithValue("@nit_supervisor", DBNull.Value);
                    sqlCmd.Parameters.AddWithValue("@nit_gerente", empleado.nit_gerente);
                    sqlCmd.Parameters.AddWithValue("@Puesto", "Supervisor");
                }
                else if (empleado.puesto == "Vendedor")
                {
                    sqlCmd.Parameters.AddWithValue("@nit_supervisor", empleado.nit_supervisor);
                    sqlCmd.Parameters.AddWithValue("@nit_gerente", DBNull.Value);
                    sqlCmd.Parameters.AddWithValue("@Puesto", "Vendedor");
                }
                sqlCmd.ExecuteNonQuery();
                sqlCon.Close();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult CargarEmpleados()
        {
            try
            {
                using (SqlConnection sqlcon = new SqlConnection(connectionString))
                {
                    if (Request.Files.Count > 0)
                    {
                        var xmlFile = Request.Files[0];

                        if (xmlFile != null && xmlFile.ContentLength > 0)
                        {
                            XmlDocument xmlDocument = new XmlDocument();
                            xmlDocument.Load(xmlFile.InputStream);
                            XmlNodeList EmpleadoNodes = xmlDocument.SelectNodes("definicion/empleado");

                            foreach (XmlNode empleado in EmpleadoNodes)
                            {
                                sqlcon.Open();
                                string query = "insert into Empleado values(@nit, @nombres, @apellidos, @pass, @fecha, @numDom, @numCel, @correo, @direccion, @nit_supervisor, @nit_gerente, @Puesto)";
                                SqlCommand sqlcom = new SqlCommand(query, sqlcon);
                                sqlcom.Parameters.AddWithValue("@nit", empleado["NIT"].InnerText);
                                sqlcom.Parameters.AddWithValue("@nombres", empleado["nombres"].InnerText);
                                sqlcom.Parameters.AddWithValue("@apellidos", empleado["apellidos"].InnerText);
                                sqlcom.Parameters.AddWithValue("@pass", empleado["pass"].InnerText);
                                sqlcom.Parameters.AddWithValue("@fecha", Convert.ToDateTime(empleado["nacimiento"].InnerText));
                                sqlcom.Parameters.AddWithValue("@numDom", Convert.ToInt32(empleado["telefono"].InnerText));
                                sqlcom.Parameters.AddWithValue("@numCel", Convert.ToInt32(empleado["celular"].InnerText));
                                sqlcom.Parameters.AddWithValue("@correo", empleado["email"].InnerText);
                                sqlcom.Parameters.AddWithValue("@direccion", empleado["direccion"].InnerText);

                                //si es un gerente
                                if (Convert.ToInt32(empleado["codigo_puesto"].InnerText) == 3)
                                {
                                    sqlcom.Parameters.AddWithValue("@nit_supervisor", DBNull.Value);
                                    sqlcom.Parameters.AddWithValue("@nit_gerente", DBNull.Value);
                                    sqlcom.Parameters.AddWithValue("@Puesto", "Gerente");
                                }
                                else if (Convert.ToInt32(empleado["codigo_puesto"].InnerText) == 2)
                                {
                                    sqlcom.Parameters.AddWithValue("@nit_supervisor", DBNull.Value);
                                    sqlcom.Parameters.AddWithValue("@nit_gerente", empleado["codigo_jefe"].InnerText);
                                    sqlcom.Parameters.AddWithValue("@Puesto", "Supervisor");
                                }
                                else if (Convert.ToInt32(empleado["codigo_puesto"].InnerText) == 1)
                                {
                                    sqlcom.Parameters.AddWithValue("@nit_supervisor", empleado["codigo_jefe"].InnerText);
                                    sqlcom.Parameters.AddWithValue("@nit_gerente", DBNull.Value);
                                    sqlcom.Parameters.AddWithValue("@Puesto", "Vendedor");
                                }
                                sqlcom.ExecuteNonQuery();
                            }

                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

Fase2_ipcvacas/Views/Empleado/Create.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model Fase2_ipcvacas.Models.ViewModels.EmpleadoViewModel

@{
    ViewBag.Title = "Crear";
}

<div class="container">

    <div class="pb-3 pt-3">
        <h2>Crear Empleado</h2>
    </div>

    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div>
                    <h4>Gerente/Supervisor/Vendedor</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.nit, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.nit, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nit, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.nombres, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nombres, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.pass, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.pass, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.pass, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.fecha_nacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.fecha_nacimiento, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.fecha_nacimiento, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.numero_domicilio, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.numero_domicilio, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.numero_domicilio, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.numero_celular, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.numero_celular, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.numero_celular, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.puesto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @{
                                List<SelectListItem> listItems = new List<SelectListItem>();
                                listItems.Add(new SelectListItem { Text = "Vendedor", Value = "Vendedor" });
                                listItems.Add(new SelectListItem { Text = "Supervisor", Value = "Supervisor" });
                                listItems.Add(new SelectListItem { Text = "Gerente", Value = "Gerente" });
                            }
                            @Html.DropDownListFor(model => model.puesto, listItems, "Seleccionar puesto...")
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.nit_supervisor, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.nit_supervisor, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nit_supervisor, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.nit_gerente, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.nit_gerente, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.nit_gerente, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Crear" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }

            <div class="pt-4">
                <a class="btn btn-primary" href="@Url.Action("Index", "Empleado")">Volver a empleados</a>
            </div>
        </div>
    </div>
</div>

Fase2_ipcvacas/Views/Empleado/Index.cshtml
@{ 
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
}

<div class="text-center pb-3 pt-3">
    <div>
        <h2>Empleados</h2>
    </div>

    @using (Html.BeginForm("CargarEmpleados", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <p>Cargar empleados(.xml)</p>
        <input type="file" name="file" />
        <input type="submit" name="Submit" id="Submit" value="Subir" />
    }
</div>

<div>
    <table class="table table-bordered text-center table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">NIT</th>
                <th scope="col">Nombres</th>
                <th scope="col">Apellidos</th>
                <th scope="col">Contraseña</th>
                <th scope="col">Fecha Nac.</th>
                <th scope="col">Número de domicilio</th>
                <th scope="col">Número de celular</th>
                <th scope="col">Correo</th>
                <th scope="col">Dirección</th>
            </tr>
        </thead>
        

        @for (int i = 0; i < Model.Rows.Count; i++)
        {
            <tr>
                <td>@Model.Rows[i][0]</td>
                <td>@Model.Rows[i][1]</td>
                <td>@Model.Rows[i][2]</td>
                <td>@Model.Rows[i][3]</td>
                <td>@Model.Rows[i][4]</td>
                <td>@Model.Rows[i][5]</td>
                <td>@Model.Rows[i][6]</td>
                <td>@Model.Rows[i][7]</td>
                <td>@Model.Rows[i][8]</td>
            </tr>
        }

    </table>
</div>


<a class="btn btn-primary" href="@Url.Action("Create", "Empleado")">Agregar empleado</a>

Fase2_ipcvacas/Views/Empleado/InicioEmpleado.cshtml
@model Fase2_ipcvacas.Models.ViewModels.EmpleadoViewModel
@{
    if (Session["userPuesto"].ToString().Equals("Vendedor"))
    {
        Layout = "~/Views/Shared/_VendedorLayout.cshtml";
    }
    else if (Session["userPuesto"].ToString().Equals("Gerente") || Session["userPuesto"].ToString().Equals("Supervisor"))
    {
        Layout = "~/Views/Shared/_EmpleadoLayout.cshtml";
    }
}

<div>
    <h1>@Model.correo</h1>
</div>