Fase2_ipcvacas/Models/ViewModels/ClienteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

//modelo originalmente pensado solo para personas individuales, pero dado a que comparten los mismos atributos con Empresa se generalizó el modelo para ambos.

namespace Fase2_ipcvacas.Models.ViewModels
{
    public class ClienteViewModel
    {
        [Required]
        [StringLength(9)]
        [DisplayName("Nit")]
        public string Nit { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Nombres")]
        public string Nombres { get; set; }

        [StringLength(50)]
        [DisplayName("Apellidos (Omitir si es empresa)")]
        public string Apellidos { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "La {0} debe tener al menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        public string Pass { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Fecha de nacimiento/Inicio de operaciones")]
        public DateTime Fecha_nacimiento { get; set; }

        [DisplayName("Número de domicilio")]
        public int Numero_domicilio { get; set; }

        [Required]
        [DisplayName("Número de celular")]
        public int Numero_celular { get; set; }

        [Required]
        [StringLength(50)]
        [EmailAddress]
        [DisplayName("Correo electrónico")]
        public string Correo { get; set; }

        public string TipoCliente { get; set; }

        [Required]
        public int CodigoCiudad { get; set; }
    }
}

Fase2_ipcvacas/Controllers/ClienteController.cs
using Fase2_ipcvacas.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Fase2_ipcvacas.Controllers
{
    public class ClienteController : Controller
    {
        string connectionString = @"Data Source=DESKTOP-UUIAD81; Initial Catalog= proyecto_ipc2beta4; Integrated Security=SSPI; MultipleActiveResultSets=true";

        public ActionResult InicioCliente(ClienteViewModel cliente)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "select * from Persona_Indiv where nit = @nit";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@nit", Session["userNit"].ToString());
                using (SqlDataReader sdr = sqlCmd.ExecuteReader())
                {
                    if (sdr.Read()) //en este caso se usa if porque solo se obtiene un resultado
                    {
                        cliente.Correo = sdr[6].ToString();
                    }
                }
                sqlCon.Close();
            }

            return View(cliente);
        }

        public ActionResult Index()
        {
            DataTable dbPersonas = new DataTable();
            DataTable dbEmpresas = new DataTable();

            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string queryPersona = "SELECT * FROM Persona_Indiv where apellidos is not null";
                string queryEmpresa = "SELECT * FROM Persona_Indiv where apellidos is null";

                SqlDataAdapter sqlDaPersona = new SqlDataAdapter(queryPersona, sqlCon);
                sqlDaPersona.Fill(dbPersonas);

                SqlDataAdapter sqlDaEmpresa = new SqlDataAdapter(queryEmpresa, sqlCon);
                sqlDaEmpresa.Fill(dbEmpresas);
                sqlCon.Close();
            }

            Session.Add("TablaPersonas", dbPersonas);
            Session.Add("TablaEmpresas", dbEmpresas);

            return View();
        }

        [HttpPost]
        public ActionResult CargarClientes()
        {
            try
            {
                using (SqlConnection sqlcon = new SqlConnection(connectionString))
                {
                    if (Request.Files.Count > 0)
                    {
                        var xmlFile = Request.Files[0];

                        if (xmlFile != null && xmlFile.ContentLength > 0)
                        {
                            XmlDocument xmlDocument = new XmlDocument();
                            xmlDocument.Load(xmlFile.InputStream);
                            XmlNodeList ClienteNodes = xmlDocument.SelectNodes("definicion/cliente");
                            XmlNodeList DepaNodes = xmlDocument.SelectNodes("definicion/depto");
                            XmlNodeList CityNodes = xmlDocument.SelectNodes("definicion/ciudad");

                            foreach (XmlNode depa in DepaNodes)
                            {
                                sqlcon.Open();
                                string queryDepa = "insert into Departamento values(@codigo, @nombre)";
                                SqlCommand sqlcom = new SqlCommand(queryDepa, sqlcon);
                                sqlcom.Parameters.AddWithValue("@codigo", Convert.ToInt32(depa["codigo"].InnerText));
                                sqlcom.Parameters.AddWithValue("@nombre", depa["nombre"].InnerText);
                                sqlcom.ExecuteNonQuery();
                                sqlcon.Close();
                            }

                            foreach (XmlNode city in CityNodes)
                            {
                                sqlcon.Open();
                                string queryCity = "insert into Ciudad values(@codigo, @nombre, @codigoDepa)";
                                SqlCommand sqlcom = new SqlCommand(queryCity, sqlcon);
                                sqlcom.Parameters.AddWithValue("@codigo", Convert.ToInt32(city["codigo"].InnerText));
                                sqlcom.Parameters.AddWithValue("@nombre", city["nombre"].InnerText);
                                sqlcom.Parameters.AddWithValue("@codigoDepa", Convert.ToInt32(city["codigo_departamento"].InnerText));
                                sqlcom.ExecuteNonQuery();
                                sqlcon.Close();
                            }

                            foreach (XmlNode cliente in ClienteNodes)
                            {

                                sqlcon.Open();
                                string queryCliente = "insert into Persona_Indiv values(@nit, @nombres, @apellidos, '12345', @fecha, @numDom, @numCel, @correo, @cod_ciudad, @direccion)";
                                
                                SqlCommand sqlcom = new SqlCommand(queryCliente, sqlcon);
                                sqlcom.Parameters.AddWithValue("@nit", cliente["NIT"].InnerText);
                                sqlcom.Parameters.AddWithValue("@nombres", cliente["nombres"].InnerText);
                                sqlcom.Parameters.AddWithValue("@apellidos", cliente["apellidos"].InnerText);
                                sqlcom.Parameters.AddWithValue("@fecha", Convert.ToDateTime(cliente["nacimiento"].InnerText));
                                sqlcom.Parameters.AddWithValue("@numDom", Convert.ToInt32(cliente["telefono"].InnerText));
                                sqlcom.Parameters.AddWithValue("@numCel", Convert.ToInt32(cliente["celular"].InnerText));
                                sqlcom.Parameters.AddWithValue("@correo", cliente["email"].InnerText);
                                sqlcom.Parameters.AddWithValue("@cod_ciudad", Convert.ToInt32(cliente["ciudad"].InnerText));
                                sqlcom.Parameters.AddWithValue("@direccion", cliente["direccion"].InnerText);
                                sqlcom.ExecuteNonQuery();
                                sqlcon.Close();

                                sqlcon.Open();
                                string queryCredito = "insert into Credito values(@limite, @restante, @nit, @dias)";
                                SqlCommand sqlcomCredito = new SqlCommand(queryCredito, sqlcon);
                                sqlcomCredito.Parameters.AddWithValue("@limite", Convert.ToDecimal(cliente["limite_credito"].InnerText));
                                sqlcomCredito.Parameters.AddWithValue("@restante", Convert.ToDecimal(cliente["limite_credito"].InnerText));
                                sqlcomCredito.Parameters.AddWithValue("@nit", cliente["NIT"].InnerText);
                                sqlcomCredito.Parameters.AddWithValue("@dias", Convert.ToInt32(cliente["dias_credito"].InnerText));
                                sqlcomCredito.ExecuteNonQuery();
                                sqlcon.Close();
                            }

                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

Fase2_ipcvacas/Views/Cliente/Index.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "ListarClientes";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    System.Data.DataTable Personas = Session["TablaPersonas"] as System.Data.DataTable;
    System.Data.DataTable Empresas = Session["TablaEmpresas"] as System.Data.DataTable;
}

<div class="container-fluid pt-3">
    <div class="row">
        <div class="col-lg-6">
            <div class="text-center">
                <h2>Personas</h2>
            </div>

            <div class="text-center pb-3">
                @using (Html.BeginForm("CargarClientes", "Cliente", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <p>Cargar clientes(personas o empresas)(.xml)</p>
                    <input type="file" name="file" />
                    <input type="submit" name="Submit" id="Submit" value="Subir" />
                }
            </div>

            <table class="table table-bordered text-center table-hover table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#NIT</th>
                        <th scope="col">Nombres</th>
                        <th scope="col">Apellidos</th>
                        <th scope="col">Password</th>
                        <th scope="col">Fecha Nac.</th>
                        <th scope="col">Número Dom.</th>
                        <th scope="col">Número cel.</th>
                        <th scope="col">Corrreo</th>
                        <th scope="col">Ciudad</th>
                        <th scope="col">Dirección</th>
                    </tr>
                </thead>

                <tbody>
                    @for (int i = 0; i < Personas.Rows.Count; i++)
                    {
                        <tr>
                            <th scope="row">@Personas.Rows[i][0] </th>
                            <td>@Personas.Rows[i][1] </td>
                            <td>@Personas.Rows[i][2]</td>
                            <td>@Personas.Rows[i][3]</td>
                            <td>@Personas.Rows[i][4]</td>
                            <td>@Personas.Rows[i][5]</td>
                            <td>@Personas.Rows[i][6]</td>
                            <td>@Personas.Rows[i][7]</td>
                            <td>@Personas.Rows[i][8]</td>
                            <td>@Personas.Rows[i][9]</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="col-lg-6">
            <div class="text-center">
                <h2>Empresas</h2>
            </div>

            <div class="text-center pb-3">
                ...
            </div>

            <table class="table table-bordered text-center table-hover table-sm">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#NIT</th>
                        <th scope="col">Nombres</th>
                        <th scope="col">Password</th>
                        <th scope="col">Fecha Inicio.</th>
                        <th scope="col">Número Dom.</th>
                        <th scope="col">Número cel.</th>
                        <th scope="col">Corrreo</th>
                        <th scope="col">Ciudad</th>
                        <th scope="col">Dirección</th>
                    </tr>
                </thead>

                <tbody>
                    @for (int i = 0; i < Empresas.Rows.Count; i++)
                    {
                        <tr>
                            <th scope="row">@Empresas.Rows[i][0] </th>
                            <td>@Empresas.Rows[i][1] </td>
                            <td>@Empresas.Rows[i][3]</td>
                            <td>@Empresas.Rows[i][4]</td>
                            <td>@Empresas.Rows[i][5]</td>
                            <td>@Empresas.Rows[i][6]</td>
                            <td>@Personas.Rows[i][7]</td>
                            <td>@Personas.Rows[i][8]</td>
                            <td>@Personas.Rows[i][9]</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Fase2_ipcvacas/Views/Cliente/InicioCliente.cshtml
@model Fase2_ipcvacas.Models.ViewModels.ClienteViewModel

@{
    ViewBag.Title = "InicioCliente";
    Layout = "~/Views/Shared/_ClienteLayout.cshtml";
}

<div>
    <h1>@Model.correo</h1>
</div>