Fase2_ipcvacas/Controllers/AdminController.cs
using Fase2_ipcvacas.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fase2_ipcvacas.Controllers
{
    public class AdminController : Controller
    {
        string connectionString = @"Data Source=DESKTOP-UUIAD81; Initial Catalog= proyecto_ipc2beta4; Integrated Security=SSPI";

        public ActionResult IncioAdmin(AdminViewModel admin)
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();
                string query = "select * from Administrador where nombre = @name";
                SqlCommand sqlCmd = new SqlCommand(query, sqlCon);
                sqlCmd.Parameters.AddWithValue("@name", Session["userAdmin"] as string);
                using (SqlDataReader sdr = sqlCmd.ExecuteReader())
                {
                    if (sdr.Read()) //en este caso se usa if porque solo se obtiene un resultado
                    {
                        admin.Nombre = sdr[1].ToString();
                    }
                }
                sqlCon.Close();
            }

            return View(admin);
        }
    }
}

Fase2_ipcvacas/Controllers/CuentaController.cs
using Fase2_ipcvacas.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fase2_ipcvacas.Controllers
{
    public class CuentaController : Controller
    {
        string connectionString = @"Data Source=DESKTOP-UUIAD81; Initial Catalog= proyecto_ipc2beta4; Integrated Security=SSPI; MultipleActiveResultSets=true";

        public ActionResult Ingresar() //login
        {
            ViewBag.Title = "Ingreso";
            return View();
        }

        [HttpPost]
        public ActionResult Ingresar(CuentaViewModel datos) //login
        {
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                
                sqlCon.Open();
                string sqlQuery = "select nit, pass, Puesto from Empleado where nit = @nit and pass = @pass";
                string queryAdmin = "select nombre, pass from Administrador where pass = @passAdmin";
                string queryCliente = "select nit, pass from Persona_Indiv where nit =@nitCliente and pass=@passCliente";
                string queryEmpresa = "select nit, pass from Empresa where nit = @nitEmpresa and pass = @passEmpresa";

                SqlCommand sqlCmd = new SqlCommand(sqlQuery, sqlCon);
                sqlCmd.Parameters.AddWithValue("@nit", datos.nit);
                sqlCmd.Parameters.AddWithValue("@pass", datos.pass);

                SqlCommand sqlCmdAdmin = new SqlCommand(queryAdmin, sqlCon);
                sqlCmdAdmin.Parameters.AddWithValue("@passAdmin", datos.pass);

                SqlCommand sqlCmdCliente = new SqlCommand(queryCliente, sqlCon);
                sqlCmdCliente.Parameters.AddWithValue("@nitCliente", datos.nit);
                sqlCmdCliente.Parameters.AddWithValue("@passCliente", datos.pass);

                SqlCommand sqlCmdEmpresa = new SqlCommand(queryEmpresa, sqlCon);
                sqlCmdEmpresa.Parameters.AddWithValue("@nitEmpresa", datos.nit);
                sqlCmdEmpresa.Parameters.AddWithValue("@passEmpresa", datos.pass);

                SqlDataReader sdrEmpleado = sqlCmd.ExecuteReader();
                SqlDataReader sdrAdmin = sqlCmdAdmin.ExecuteReader();
                SqlDataReader sdrCliente = sqlCmdCliente.ExecuteReader();
                SqlDataReader sdrEmpresa = sqlCmdEmpresa.ExecuteReader();

                if (sdrEmpleado.Read())
                {
                    Session["userNit"] = datos.nit.ToString();
                    Session["userPuesto"] = sdrEmpleado[2].ToString();

                    //if (sdr[2].ToString().Equals("Gerente"))
                    //{
                    //    return RedirectToAction("Index", "Empleado");
                    //}
                    //else if (sdr[2].ToString().Equals("Supervisor"))
                    //{

                    //}
                    return RedirectToAction("InicioEmpleado", "Empleado");
                }
                else if (sdrAdmin.Read())
                {
                    Session["userAdmin"] = datos.nit.ToString(); //se usará el campo nit para el nombre de usuario del admin
                    return RedirectToAction("IncioAdmin", "Admin");
                }
                else if (sdrCliente.Read())
                {
                    Session["userNit"] = datos.nit.ToString();

                    return RedirectToAction("InicioCliente", "Cliente");
                }
                else if (sdrEmpresa.Read())
                {
                    Session["userNit"] = datos.nit.ToString();

                    return RedirectToAction("InicioEmpresa", "Empresa");
                }
                else
                {
                    ViewData["Mensaje"] = "Datos incorrectos";
                }
                
                sqlCon.Close();
                return View();
                    
            }
        }

        public ActionResult Salir() //cerrar sesión
        {
            Session["userNit"] = null;
            Session["userPuesto"] = null;
            Session["userAdmin"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Registrar() //registrarse
        {
            return View();
        }
    }
}

Fase2_ipcvacas/Controllers/OrdenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fase2_ipcvacas.Controllers
{
    public class OrdenController : Controller
    {
        //string connectionString = @"Data Source=DESKTOP-UUIAD81; Initial Catalog= proyecto_ipc2beta4; Integrated Security=SSPI; MultipleActiveResultSets=true";
        
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult HomeOrdenes()
        {
            return View();
        }
        
    }
}

Fase2_ipcvacas/Controllers/ProductoController.cs
using Fase2_ipcvacas.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Xml;

namespace Fase2_ipcvacas.Controllers
{
    public class ProductoController : Controller
    {
        string connectionString = @"Data Source=DESKTOP-UUIAD81; Initial Catalog= proyecto_ipc2beta4; Integrated Security=SSPI; MultipleActiveResultSets=true";

        public ActionResult Index()
        {
            DataTable dbProductos = new DataTable();
            DataTable dbListasPrecios = new DataTable();
            using (SqlConnection sqlCon = new SqlConnection(connectionString))
            {
                sqlCon.Open();

                string query = "select Producto.codigo, Producto.nombre, Producto.descripcion, Producto.id_listaPrecios, " +
                    "CategoriaProducto.nombre_categoria from Producto inner join CategoriaProducto on Producto.id_categoria = CategoriaProducto.id";

                string queryListasPrecios = "select ListaPrecios.id, CAST(ListaPrecios.fecha_inicio as date), " +
                    "CAST(ListaPrecios.fecha_vencimiento as date), ListaPrecios.es_vigente from ListaPrecios";

                SqlDataAdapter sqlDa = new SqlDataAdapter(query, sqlCon);
                SqlDataAdapter sqlDaListasPrecios = new SqlDataAdapter(queryListasPrecios, sqlCon);
                sqlDa.Fill(dbProductos);
                sqlDaListasPrecios.Fill(dbListasPrecios);

                sqlCon.Close();

                Session.Add("ListasPrecios", dbListasPrecios);
            }

            return View(dbProductos);
        }

        public ActionResult HabilitarLista(int idlista)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "update ListaPrecios set es_vigente = 'True' where id = @idlista;";
                SqlCommand sqlcom = new SqlCommand(query, sqlcon);
                sqlcom.Parameters.AddWithValue("@idlista", idlista);
                sqlcom.ExecuteNonQuery();
                sqlcon.Close();
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeshabilitarLista(int idlista)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "update ListaPrecios set es_vigente = 'False' where id = @idlista;";
                SqlCommand sqlcom = new SqlCommand(query, sqlcon);
                sqlcom.Parameters.AddWithValue("@idlista", idlista);
                sqlcom.ExecuteNonQuery();
                sqlcon.Close();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult CargarProductos()
        {
            try
            {
                using (SqlConnection sqlcon = new SqlConnection(connectionString))
                {
                    if (Request.Files.Count > 0)
                    {
                        var xmlFile = Request.Files[0];

                        if (xmlFile != null && xmlFile.ContentLength > 0)
                        {
                            XmlDocument xmlDocument = new XmlDocument();
                            xmlDocument.Load(xmlFile.InputStream);
                            XmlNodeList ProductoNodes = xmlDocument.SelectNodes("definicion/producto");
                            XmlNodeList CategoriaNodes = xmlDocument.SelectNodes("definicion/categoria");

                            foreach (XmlNode categoria in CategoriaNodes)
                            {
                                sqlcon.Open();
                                string query = "insert into CategoriaProducto values(@codigo, @categoria)";
                                SqlCommand sqlcom = new SqlCommand(query, sqlcon);
                                sqlcom.Parameters.AddWithValue("@codigo", Convert.ToInt32(categoria["codigo"].InnerText));
                                sqlcom.Parameters.AddWithValue("@categoria", categoria["nombre"].InnerText);
                                sqlcom.ExecuteNonQuery();
                                sqlcon.Close();
                            }

                            foreach (XmlNode producto in ProductoNodes)
                            {
                                sqlcon.Open();
                                string queryProducto = "insert into Producto values(@codigo, @nombre, @descripcion, '', 0, @idlista, @idcategoria)";
                                SqlCommand sqlcomProducto = new SqlCommand(queryProducto, sqlcon);
                                sqlcomProducto.Parameters.AddWithValue("@codigo", Convert.ToInt32(producto["codigo"].InnerText));
                                sqlcomProducto.Parameters.AddWithValue("@nombre", producto["nombre"].InnerText);
                                sqlcomProducto.Parameters.AddWithValue("@descripcion", producto["descripcion"].InnerText);
                                sqlcomProducto.Parameters.AddWithValue("@idlista", DBNull.Value);
                                sqlcomProducto.Parameters.AddWithValue("@idcategoria", Convert.ToInt32(producto["categoria"].InnerText));
                                sqlcomProducto.ExecuteNonQuery();
                                sqlcon.Close();
                            }
                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult CargarListas()
        {

            return View();
        }
    }
}

Fase2_ipcvacas/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">DIPROMA - Administrador</a>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("IncioAdmin", "Admin")" class="nav-link">Inicio</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index", "Empleado")" class="nav-link">Empleados</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index", "Producto")" class="nav-link">Productos</a></li>
                    <li class="nav-item"><a href="@Url.Action("Index", "Cliente")" class="nav-link">Clientes</a></li>
                    <li class="nav-item"><a href="/Home/Contact" class="nav-link">Reportes</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Vehículos</a></li>
                </ul>
            </div>
            <div id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("Salir", "Cuenta")" class="nav-link">Salir</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="conteiner body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Fase2_ipcvacas/Views/Shared/_ClienteLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">DIPROMA</a>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="/" class="nav-link">Inicio</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Tienda</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Órdenes</a></li>
                </ul>
            </div>
            <div id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("Salir", "Cuenta")" class="nav-link">Salir</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Fase2_ipcvacas/Views/Shared/_EmpleadoLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">DIPROMA - @Session["userPuesto"].ToString()</a>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("InicioEmpleado", "Empleado")" class="nav-link">Inicio</a></li>
                    <li class="nav-item"><a href="@Url.Action("HomeOrdenes", "Orden")" class="nav-link">Órdenes</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Vehículo</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Metas</a></li>
                </ul>
            </div>
            <div id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("Salir", "Cuenta")" class="nav-link">Cerrar sesión</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Fase2_ipcvacas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">DIPROMA</a>
            <div id="navbarSupportedContent">
                
                <ul class="nav navbar-nav navbar-right mr-auto">
                    <li class="nav-item"><a href="/Account/Register" id="registerLink" class="nav-link">Registrarse</a></li>
                    <li class="nav-item"><a href="@Url.Action("Ingresar", "Cuenta")" id="loginLink" class="nav-link">Ingresar</a></li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>

Fase2_ipcvacas/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">DIPROMA</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="nav navbar-nav navbar-right mr-auto">
                    <li class="nav-item"><a href="@Url.Action("Index", "Home")" id="registerLink" class="nav-link">Volver a Inicio</a></li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Fase2_ipcvacas/Views/Shared/_VendedorLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            </button>
            <a class="navbar-brand" href="/">DIPROMA - @Session["userPuesto"].ToString()</a>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("IncioEmpleado", "Empleado")" class="nav-link">Inicio</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Órdenes</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">Metas</a></li>
                </ul>
            </div>
            <div id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item"><a href="@Url.Action("Salir", "Cuenta")" class="nav-link">Cerrar sesión</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>